### PR TITLE
[EEN-14247] Update SSO descriptions.

### PR DESCRIPTION
**Pull request by michalboruch**
Update:
- Account settings
- AAA SSO section

### CODE REVIEW

**Comment by mcotton** [comment]
I can't get to build cleanly under docker-compose.  Can you confirm that it is working for you and that all your changes are checked-in?

**Comment by michalboruch** [comment]
I was unable to get css'es locally, production is doing fine with a new build, so I assumed that we're good. But I can wait with this PR.
There is something with middleman/sprockets.
@mrauer Could you please take a look?

**Comment by mrauer** [comment]
I'm having a look @michalboruch

**Comment by michalboruch** [comment]
Thanks, but I'm still getting
```
Request URL: http://127.0.0.1:4567/stylesheets/screen.css
Request Method: GET
Status Code: 404 Not Found
```

**Comment by mrauer** [comment]
Right, no need to go to that URL. Open the index.html in the generated build directory.

Local server will be fixed as of https://eagleeyenetworks.atlassian.net/browse/EEN-14460

**Comment by mcotton** [comment]
If we are going to change how to access the local server, please update the README so that people follow the correct instructions.

I don't think issue  https://eagleeyenetworks.atlassian.net/browse/EEN-14460 has anything to do with the css breaking on localhost.  Am I missing something?

**Comment by mrauer** [comment]
Right https://eagleeyenetworks.atlassian.net/browse/EEN-14504

**Comment by janeek1995** [comment]
:+1:

**Comment by michalboruch** [comment]
rebased

**Pull request merged**
